#!/usr/bin/env bash
# iptables.sh — Unraid host firewall
#
# Deployed to : /boot/config/scripts/iptables.sh
# Called from : /boot/config/go on every boot
# Generated by: secure_oss unraid/harden.sh
#
# PURPOSE
# -------
# Applies iptables rules to protect the Unraid HOST. This script only
# manages the INPUT chain (traffic destined for the Unraid OS itself).
# The FORWARD chain is left untouched so Docker and libvirt can manage
# container and VM routing without interference.
#
# DOCKER / CONTAINER NOTE
# -----------------------
# Docker container ports mapped with -p (e.g. -p 8080:80) go through the
# FORWARD and DOCKER chains, NOT through INPUT. This script does NOT protect
# those ports. To restrict container port access to the local subnet only,
# use the DOCKER-USER chain section at the bottom of this script.
#
# IDEMPOTENCY
# -----------
# This script flushes and re-applies all rules on each run. Safe to call
# repeatedly (e.g. after a network change or manual re-run).

set -euo pipefail

# ===========================================================================
# CONFIGURATION
# Edit these variables to match your network. harden.sh sets them
# automatically during initial setup — only edit manually if your
# network layout changes.
# ===========================================================================

# Local subnet that is allowed to reach Samba shares, NFS, and the web UI.
# Set to a specific subnet (e.g. 192.168.1.0/24) or "any" to allow all.
LOCAL_SUBNET="@@LOCAL_SUBNET@@"

# Unraid web UI ports (HTTP and HTTPS)
WEB_HTTP_PORT="@@WEB_HTTP_PORT@@"
WEB_HTTPS_PORT="@@WEB_HTTPS_PORT@@"

# SSH port (0 to block SSH entirely)
SSH_PORT="@@SSH_PORT@@"

# Allow SMB (Samba file shares) from LOCAL_SUBNET (1=yes, 0=no)
ALLOW_SMB="@@ALLOW_SMB@@"

# Allow NFS from LOCAL_SUBNET (1=yes, 0=no)
ALLOW_NFS="@@ALLOW_NFS@@"

# WireGuard UDP port — leave empty if WireGuard is not configured
WIREGUARD_PORT="@@WIREGUARD_PORT@@"

# ===========================================================================
# Helpers
# ===========================================================================

ipt() { iptables "$@"; }

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [iptables] $*" | tee -a /var/log/secure_oss_fw.log 2>/dev/null || true; }

# ===========================================================================
# Flush and reset
# ===========================================================================

log "Applying Unraid host firewall rules..."

# Flush existing rules in the chains we manage
ipt -F INPUT
ipt -F OUTPUT
# Do NOT flush FORWARD — Docker and libvirt manage it

# Remove any custom chains we previously created (idempotency)
ipt -F SECURE_OSS_INPUT 2>/dev/null || true
ipt -X SECURE_OSS_INPUT 2>/dev/null || true

# ===========================================================================
# Default policies
# INPUT  : DROP  — block everything not explicitly allowed
# FORWARD: ACCEPT — let Docker/libvirt manage container/VM routing
# OUTPUT : ACCEPT — unrestricted outbound from the host
# ===========================================================================

ipt -P INPUT  DROP
ipt -P FORWARD ACCEPT
ipt -P OUTPUT ACCEPT

# ===========================================================================
# INPUT rules
# ===========================================================================

# --- Loopback ---
# Allow all traffic on the loopback interface. Many services on the host
# communicate with each other via 127.0.0.1 and must not be blocked.
ipt -A INPUT -i lo -j ACCEPT

# --- Established and related ---
# Allow return traffic for connections the host initiated outbound
# (e.g. package downloads, NTP, DNS lookups, WireGuard tunnel traffic).
# This is the conntrack rule that makes stateful firewalling work.
ipt -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# --- ICMP (ping) ---
# Allow ICMP echo requests (ping) so the host is reachable for basic
# network diagnostics. Rate-limited to 10/second to prevent ping floods.
ipt -A INPUT -p icmp --icmp-type echo-request -m limit --limit 10/second -j ACCEPT

# --- Unraid Web UI ---
# Restrict to LOCAL_SUBNET. The Unraid management interface should never
# be exposed on the WAN side of a router.
if [[ "${LOCAL_SUBNET}" == "any" ]]; then
    ipt -A INPUT -p tcp --dport "${WEB_HTTP_PORT}"  -j ACCEPT
    ipt -A INPUT -p tcp --dport "${WEB_HTTPS_PORT}" -j ACCEPT
else
    ipt -A INPUT -p tcp -s "${LOCAL_SUBNET}" --dport "${WEB_HTTP_PORT}"  -j ACCEPT
    ipt -A INPUT -p tcp -s "${LOCAL_SUBNET}" --dport "${WEB_HTTPS_PORT}" -j ACCEPT
fi
log "Web UI: allowed on ports ${WEB_HTTP_PORT}/${WEB_HTTPS_PORT} from ${LOCAL_SUBNET}"

# --- SSH ---
if [[ "${SSH_PORT}" != "0" && -n "${SSH_PORT}" ]]; then
    if [[ "${LOCAL_SUBNET}" == "any" ]]; then
        ipt -A INPUT -p tcp --dport "${SSH_PORT}" -j ACCEPT
    else
        ipt -A INPUT -p tcp -s "${LOCAL_SUBNET}" --dport "${SSH_PORT}" -j ACCEPT
    fi
    log "SSH: allowed on port ${SSH_PORT} from ${LOCAL_SUBNET}"
else
    log "SSH: blocked (SSH_PORT=0 or unset)"
fi

# --- Samba / SMB ---
# SMB shares should only be accessible from the local network.
# Ports: 137/udp (NetBIOS name), 138/udp (NetBIOS datagram),
#        139/tcp (NetBIOS session), 445/tcp (SMB over TCP — primary)
if [[ "${ALLOW_SMB}" == "1" ]]; then
    if [[ "${LOCAL_SUBNET}" == "any" ]]; then
        ipt -A INPUT -p tcp --dport 445 -j ACCEPT
        ipt -A INPUT -p tcp --dport 139 -j ACCEPT
        ipt -A INPUT -p udp --dport 137 -j ACCEPT
        ipt -A INPUT -p udp --dport 138 -j ACCEPT
    else
        ipt -A INPUT -p tcp -s "${LOCAL_SUBNET}" --dport 445 -j ACCEPT
        ipt -A INPUT -p tcp -s "${LOCAL_SUBNET}" --dport 139 -j ACCEPT
        ipt -A INPUT -p udp -s "${LOCAL_SUBNET}" --dport 137 -j ACCEPT
        ipt -A INPUT -p udp -s "${LOCAL_SUBNET}" --dport 138 -j ACCEPT
    fi
    log "SMB: allowed from ${LOCAL_SUBNET}"
else
    log "SMB: blocked (ALLOW_SMB=0)"
fi

# --- NFS ---
# NFS is disabled by default. Enable only if you use NFS mounts.
# NFS requires several ports; we open the main ones here.
# For a production NFS setup, pin rpc ports in /etc/nfs.conf and open
# those specific ports rather than using the defaults.
if [[ "${ALLOW_NFS}" == "1" ]]; then
    if [[ "${LOCAL_SUBNET}" == "any" ]]; then
        ipt -A INPUT -p tcp --dport 2049 -j ACCEPT   # NFS v3/v4
        ipt -A INPUT -p udp --dport 2049 -j ACCEPT
        ipt -A INPUT -p tcp --dport 111  -j ACCEPT   # rpcbind (portmapper)
        ipt -A INPUT -p udp --dport 111  -j ACCEPT
    else
        ipt -A INPUT -p tcp -s "${LOCAL_SUBNET}" --dport 2049 -j ACCEPT
        ipt -A INPUT -p udp -s "${LOCAL_SUBNET}" --dport 2049 -j ACCEPT
        ipt -A INPUT -p tcp -s "${LOCAL_SUBNET}" --dport 111  -j ACCEPT
        ipt -A INPUT -p udp -s "${LOCAL_SUBNET}" --dport 111  -j ACCEPT
    fi
    log "NFS: allowed from ${LOCAL_SUBNET}"
else
    log "NFS: blocked (ALLOW_NFS=0)"
fi

# --- WireGuard ---
# If WireGuard is configured on this Unraid server (acting as a VPN server),
# allow the UDP port for incoming tunnel handshakes.
if [[ -n "${WIREGUARD_PORT}" ]]; then
    ipt -A INPUT -p udp --dport "${WIREGUARD_PORT}" -j ACCEPT
    log "WireGuard: allowed UDP port ${WIREGUARD_PORT}"
fi

# --- Log and drop everything else ---
# Log unexpected inbound packets before dropping. The rate limit prevents
# log flooding. Check /var/log/kern.log or dmesg for BLOCKED entries.
ipt -A INPUT -m limit --limit 5/minute --limit-burst 10 \
    -j LOG --log-prefix "[BLOCKED INPUT] " --log-level 4
ipt -A INPUT -j DROP

log "INPUT chain: default DROP applied"

# ===========================================================================
# DOCKER-USER chain — restrict container port access to local subnet
#
# Docker maps container ports to host ports and routes them via the FORWARD
# and DOCKER chains — bypassing INPUT entirely. The DOCKER-USER chain runs
# BEFORE Docker's own DOCKER chain, giving us a place to add restrictions.
#
# The rules below drop forwarded traffic to Docker containers if the source
# is NOT the local subnet. This prevents container ports from being reachable
# from the internet even if the host sits on a public IP.
#
# Comment out this block if you intentionally expose container ports publicly.
# ===========================================================================

if iptables -L DOCKER-USER -n &>/dev/null 2>&1; then
    iptables -F DOCKER-USER

    if [[ "${LOCAL_SUBNET}" != "any" ]]; then
        # Allow container traffic from local subnet and established connections
        iptables -A DOCKER-USER -s "${LOCAL_SUBNET}" -j RETURN
        iptables -A DOCKER-USER -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN

        # Log and drop everything else headed to Docker containers
        iptables -A DOCKER-USER -m limit --limit 5/minute --limit-burst 10 \
            -j LOG --log-prefix "[BLOCKED DOCKER] " --log-level 4
        iptables -A DOCKER-USER -j DROP

        log "DOCKER-USER: container ports restricted to ${LOCAL_SUBNET}"
    else
        log "DOCKER-USER: LOCAL_SUBNET=any — container ports unrestricted"
    fi
else
    log "DOCKER-USER chain not found (Docker may not be running yet — will apply on next boot after Docker starts)"
fi

log "Firewall rules applied successfully."
log "Verify with: iptables -L INPUT -n -v"
