#!/usr/bin/env bash
# optional/wireguard-killswitch.sh — Generate a WireGuard kill-switch config
#
# Platform  : Fedora Silverblue (secureblue)
# Purpose   : Creates a WireGuard interface config with a kill-switch: firewall
#             rules that block ALL non-VPN traffic when the VPN is up, and
#             restore full access when the VPN is down. Prevents traffic leaks
#             if the VPN connection drops.
#
# This script generates a template config at:
#   /etc/wireguard/<INTERFACE>.conf
#
# You must fill in your actual VPN server details (endpoint, public key, etc.)
# before activating. See inline comments in the generated file.
#
# Usage:
#   sudo bash optional/wireguard-killswitch.sh [--interface wg0] [--dry-run]
#   sudo bash optional/wireguard-killswitch.sh --remove --interface wg0

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

WG_INTERFACE="wg0"
REMOVE_MODE=0
WG_PORT="51820"

usage() {
    cat <<EOF
Usage: sudo bash optional/wireguard-killswitch.sh [OPTIONS]

Generate a WireGuard kill-switch config template.

Options:
  --interface NAME   WireGuard interface name (default: wg0)
  --remove           Remove the generated config and disable the interface
  --dry-run          Show what would be done without making changes
  --help             Show this help

After running, edit /etc/wireguard/<INTERFACE>.conf and fill in your VPN
provider's server details, then activate with:
  sudo wg-quick up <INTERFACE>
  sudo systemctl enable wg-quick@<INTERFACE>
EOF
}

parse_args() {
    parse_common_args "$@"
    set -- "${REMAINING_ARGS[@]+"${REMAINING_ARGS[@]}"}"
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --interface)
                WG_INTERFACE="${2:?--interface requires a name}"
                shift 2
                ;;
            --remove)
                REMOVE_MODE=1
                shift
                ;;
            *)
                die "Unknown argument: $1"
                ;;
        esac
    done
}

generate_private_key() {
    # Generates a fresh WireGuard private key for the local interface.
    # In dry-run mode, returns a placeholder.
    if [[ "${DRY_RUN}" == "1" ]]; then
        echo "<GENERATED_PRIVATE_KEY>"
        return 0
    fi

    if ! command -v wg &>/dev/null; then
        die "wg not found. Install wireguard-tools: rpm-ostree install wireguard-tools && reboot"
    fi

    wg genkey
}

create_config() {
    local conf_path="/etc/wireguard/${WG_INTERFACE}.conf"

    if [[ -f "${conf_path}" ]]; then
        warn "Config already exists at ${conf_path}"
        warn "Remove it first with --remove, or edit it directly."
        return 1
    fi

    if ! command -v wg &>/dev/null && [[ "${DRY_RUN}" != "1" ]]; then
        die "wireguard-tools not installed. Run: rpm-ostree install wireguard-tools && reboot"
    fi

    log "Generating WireGuard private key..."
    local private_key
    private_key="$(generate_private_key)"

    local public_key="<DERIVED_FROM_PRIVATE_KEY>"
    if [[ "${DRY_RUN}" != "1" ]] && command -v wg &>/dev/null; then
        public_key="$(echo "${private_key}" | wg pubkey)"
        log "Your WireGuard public key (share this with your VPN provider): ${public_key}"
    fi

    local conf_content
    conf_content="# WireGuard kill-switch config — generated by secure_oss
# Interface: ${WG_INTERFACE}
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
#
# FILL IN the [Peer] section with your VPN provider's details before activating.
# Activate: sudo wg-quick up ${WG_INTERFACE}
# Enable on boot: sudo systemctl enable wg-quick@${WG_INTERFACE}

[Interface]
# Your WireGuard private key (keep this secret)
PrivateKey = ${private_key}

# Your VPN-assigned IP address (get this from your provider)
Address = 10.0.0.2/32

# DNS server to use when VPN is active — using your provider's DNS prevents leaks.
# Replace with your provider's DNS server IP.
DNS = 10.0.0.1

# Kill-switch: block all non-VPN traffic when this interface is up.
# PreUp/PostDown manage a firewall mark that routes all traffic through WireGuard.
# Traffic without the mark (i.e., not going through the tunnel) is dropped.
#
# How it works:
#   1. PreUp: add a firewall rule to drop all traffic not in routing table 51820
#   2. The WireGuard kernel module marks VPN traffic with fwmark 51820
#   3. Table 51820 routes only via the WireGuard interface
#   4. All unmarked traffic hits the drop rule
#   5. PostDown: removes the firewall rules (normal routing resumes)
PreUp = ip rule add not fwmark ${WG_PORT} table ${WG_PORT}; ip -6 rule add not fwmark ${WG_PORT} table ${WG_PORT} 2>/dev/null || true
PostDown = ip rule del not fwmark ${WG_PORT} table ${WG_PORT} 2>/dev/null || true; ip -6 rule del not fwmark ${WG_PORT} table ${WG_PORT} 2>/dev/null || true

# Also block via firewalld (belt-and-suspenders)
PreUp = firewall-cmd --add-rich-rule='rule family=ipv4 source address=0.0.0.0/0 drop' --zone=public 2>/dev/null; firewall-cmd --add-rich-rule='rule family=ipv4 destination address=<VPN_SERVER_IP>/32 accept' --zone=public 2>/dev/null || true
PostDown = firewall-cmd --remove-rich-rule='rule family=ipv4 source address=0.0.0.0/0 drop' --zone=public 2>/dev/null; firewall-cmd --remove-rich-rule='rule family=ipv4 destination address=<VPN_SERVER_IP>/32 accept' --zone=public 2>/dev/null || true

# WireGuard listening port (for the local socket, not the remote)
ListenPort = ${WG_PORT}

[Peer]
# Your VPN provider's WireGuard public key
PublicKey = REPLACE_WITH_SERVER_PUBLIC_KEY

# Allowed IPs: 0.0.0.0/0, ::/0 routes ALL traffic through the tunnel (full VPN).
# Change to a specific CIDR if you only want split-tunnel routing.
AllowedIPs = 0.0.0.0/0, ::/0

# Your VPN provider's endpoint (IP:port)
# NOTE: Replace <VPN_SERVER_IP> here AND in the PreUp/PostDown firewall rules above
Endpoint = <VPN_SERVER_IP>:51820

# Keep the connection alive through NAT firewalls
PersistentKeepalive = 25"

    write_file "${conf_path}" "${conf_content}"

    if [[ "${DRY_RUN}" != "1" ]]; then
        chmod 600 "${conf_path}"
        restorecon -v "${conf_path}" 2>/dev/null || true
    fi

    log ""
    log "Config written to ${conf_path}"
    log ""
    log "Next steps:"
    log "  1. Edit ${conf_path} and fill in [Peer] section"
    log "  2. Replace <VPN_SERVER_IP> in PreUp/PostDown with your server IP"
    log "  3. Test: sudo wg-quick up ${WG_INTERFACE}"
    log "  4. Verify: curl ifconfig.me (should show VPN IP)"
    log "  5. Enable at boot: sudo systemctl enable wg-quick@${WG_INTERFACE}"
    log ""
    log "Your public key (share with provider): ${public_key}"
}

remove_config() {
    local conf_path="/etc/wireguard/${WG_INTERFACE}.conf"

    if [[ ! -f "${conf_path}" ]]; then
        log "Config not found at ${conf_path} — nothing to remove"
        return 0
    fi

    # Stop the interface if running
    if ip link show "${WG_INTERFACE}" &>/dev/null; then
        log "Bringing down ${WG_INTERFACE}..."
        run_cmd wg-quick down "${WG_INTERFACE}" 2>/dev/null || true
    fi

    run_cmd systemctl disable "wg-quick@${WG_INTERFACE}" 2>/dev/null || true
    run_cmd rm --force "${conf_path}"

    log "WireGuard config removed for interface ${WG_INTERFACE}"
}

main() {
    parse_args "$@"
    require_root

    if [[ "${REMOVE_MODE}" -eq 1 ]]; then
        remove_config
    else
        create_config
    fi
}

main "$@"
